CONFIG_APP_NODE_ID="13"

CONFIG_APP_MEASUREMENT_PERIOD_S=60

# THREAD_ROLE=MTD

# Basis feature toggles
CONFIG_APP_PUBLISH_UPTIME=y

# Sensor mix voor ND13
CONFIG_APP_USE_DS18B20_SENSOR=n
CONFIG_APP_USE_MAX31850_SENSOR=n
CONFIG_APP_USE_SCD41_SENSOR=n
CONFIG_APP_USE_SHT41_SENSOR=n
CONFIG_APP_USE_SEN50_SENSOR=y
CONFIG_APP_USE_DSMR_SENSOR=n
CONFIG_APP_USE_BMP388_SENSOR=n
CONFIG_APP_USE_PLUVIO_SENSOR=n