CONFIG_NETWORKING=y
CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_NET_L2_OPENTHREAD=y

CONFIG_OPENTHREAD=y
CONFIG_OPENTHREAD_SHELL=y

CONFIG_MULTITHREADING=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y

CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_LOG=y
CONFIG_PRINTK=y

CONFIG_LOG_BACKEND_UART=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_SHELL_STACK_SIZE=2048

CONFIG_MAIN_STACK_SIZE=6144
CONFIG_ISR_STACK_SIZE=3072
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_OPENTHREAD_THREAD_STACK_SIZE=6144
CONFIG_OPENTHREAD_RADIO_WORKQUEUE_STACK_SIZE=1024

CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_PROCESS_THREAD=n
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_SHELL_BACKEND_SERIAL_LOG_MESSAGE_QUEUE_SIZE=32

CONFIG_I2C_SHELL=y

CONFIG_SHT4X=y

CONFIG_SENSOR_LOG_LEVEL_INF=y


# Transport = CoAP (via jouw transport_* laag)
CONFIG_APP_TRANSPORT_COAP=y

# CoAP client defaults (kunnen runtime overschreven worden en worden gepersisteerd)
CONFIG_APP_COAP_SERVER_ADDR="fdf4:c3a4:97ec:2:0:0:c0a8:105"
CONFIG_APP_COAP_SERVER_PORT=5684
CONFIG_APP_COAP_ACK_TIMEOUT_MS=800
CONFIG_APP_COAP_RETRIES=3
