CONFIG_OPENTHREAD_PANID=9232
CONFIG_OPENTHREAD_NETWORK_NAME="OT-MANNAH"
CONFIG_OPENTHREAD_XPANID="12:34:56:78:12:34:56:78"
CONFIG_OPENTHREAD_NETWORKKEY="6ac256fa944dd28b7f9a641d8449edd9"
CONFIG_OPENTHREAD_CHANNEL=20

CONFIG_OPENTHREAD_SLAAC=y
CONFIG_OPENTHREAD_PING_SENDER=y
CONFIG_OPENTHREAD_JOINER=n
CONFIG_OPENTHREAD_UPTIME=y
CONFIG_OPENTHREAD_CONFIG_PLATFORM_INFO="Zephyr"
CONFIG_OPENTHREAD_RADIO_LINK_IEEE_802_15_4_ENABLE=y
