# -------------------------------------------------
# Device Type
# -------------------------------------------------
CONFIG_OPENTHREAD_MTD=y
CONFIG_OPENTHREAD_MAX_IP_ADDR_PER_CHILD=6
CONFIG_OPENTHREAD_THREAD_STACK_SIZE=4096