# Node-identiteit
CONFIG_APP_NODE_ID="12"

# Cadence
CONFIG_APP_MEASUREMENT_PERIOD_S=60

# Thread rol
CONFIG_OPENTHREAD_MTD=y
# of:
# CONFIG_OPENTHREAD_FTD=y

# Features
CONFIG_APP_PUBLISH_UPTIME=y
CONFIG_APP_USE_SHT41_SENSOR=y